name: Branch Naming Policy Action

on:
  create:
  delete:
  pull_request:
    branches:
      - develop

jobs:
  branch-naming-policy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check Branch Name Format
        id: check_branch_format
        if: github.ref_type == 'branch' || github.ref_type == 'pull_request'
        with:
          regex: 'KAN-\d+/(feature|bug|hotfix)/[a-zA-Z-]+'
